---
title: "Postdoctoral Position in Behavioral Ecotoxicology and/or Modeling"
draft: false
categories: [job, behavior, ecotoxicology, postdocs]
---

(*Update 13/08/2024: Adding more details on eligibility and application requirements*)


The postdoctoral call from [INRAE's Agroecosystem division](https://www.inrae.fr/en/divisions/agroecosystem) is now open. If successful, the division offers a 12-month position to start in fall 2025. If you are interested my [research activities](https://rroyaute.github.io/research/current-research/#BehavTox), feel free to contact me with your CV and a brief summary of project interests. I would like to prioritize projects on behavioral ecotoxicology and / or modeling but am of course open to your suggestions and ideas. The application must be submitted by the end of September, so make sure to contact me before **August 25, 2024** (*raphael.royaute@inrae.fr*). 

### Eligibility

- No nationality restrictions
- Must have completed the PhD no later than fall 2022 (position subject to 3-years post-PhD rule as per French regulations)

## Application

Four-page application including the following:

- State-of-the-art
- Research question
- Hypotheses
- Research program and timeline

Primary project ideas revolve around applying pose-tracking to video data of soil arthropods exposed to contaminants. I am of course opened to discuss other ideas depending on feasibility within our lab.


## Salary range and benefits

- Gross salary range between 2600 and 3100 € depending on experience
- Full benefits including health care and holidays 
